version: "3"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/bogdan/data/db:/data/db
    ports:
      - "27017:27017"
